#!/bin/bash
# if "$SNAP/quake2-engine" exists we can expect this to run
# as a content snap within, say, a Quake map editor.
# On the confinement side the script runs within the parents sandbox.

QUAKE_ENGINE=yquake2

if [ -d "$SNAP/quake2-engine" ]; then
    export SNAP="${SNAP}/quake2-engine"
fi

# use zenity dialog when started without arguments
if [ "x$@" == "x" ]; then
    GAMEFILES_PATH=`zenity \
      --file-selection \
      --directory \
      --title='Select the baseq2 directory containing Quake 2 game files (pak0.pak, pak1.pak ...)'`
    
    # We actually need the parent directory
    GAMEFILES_PATH=$(dirname "${GAMEFILES_PATH}")
    exec "$SNAP/command-$QUAKE_ENGINE.wrapper" "-datadir" "$GAMEFILES_PATH"
else
    exec "$SNAP/command-$QUAKE_ENGINE.wrapper" "$@"
fi
